### ISSUE TITLE
setUp included in time limit

### ISSUE THREAD

**Issue by MGatner** [NexusPHP/tachycardia#8]
**Environment:**
* PHP version: 7.4
* Tachycardia version: 1.1.1

**Description:**
I'm not entirely sure if this is a bug but I did not notice this issue with SpeedTrap. It appears that the time to run `setUp()` is included in the test time limit - this is particularly confusing for once-run database configurations with data providers where a single data set will show as a lot slower than the others. I have tested without data providers as well to confirm it is not a fringe scenario.

**Steps to Reproduce:**
See e.g. https://github.com/duke-bluesmith/bluesmith/blob/develop/tests/controllers/JobsControllerTest.php, and the various test results at #7 

**Expected Output:**
I think the ideal scenario would be to split out the "staging" from the actual tests, and be able to report on slow staging (e.g. `setUp` and `tearDown`) with their own annotated `@timeLimit` options. Barring the difficulty of that implementation, I would like to see time limits calculated solely on my actual test methods.

**Comment by MGatner** [comment]
Looks like some helpful info here: https://github.com/johnkary/phpunit-speedtrap/issues/51

**Comment by paulbalandan** [comment]
I have read this one before and I honestly cannot look into a solution as the data passed to a `Hook` instance is very limited. The `Hook` is this extension, for example. `PHPUnit` passes only the class-string of the `TestCase` and the total execution time to each Hook instance. Plus I see no way to get the objects used by PHPUnit because of the strict separation of responsibilities implemented.

Hook extensions are added to the `TestListenerAdapter`  but is not overridable as it is an internal class. For now, I'm waiting for the promised new Event system to be implemented in PHPUnit 10. Perhaps by then we can have a better hold of variables.

**Comment by MGatner** [comment]
Okay, that is unfortunate but not unexpected. I use Infection for mutation testing which has a strong preference for randomized test order - it makes this even more annoying because I can't just ignore "the first test" because there is no way of knowing which is first.
